# Generated by Django 4.2 on 2023-06-16 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_ipaddress_alter_article_published_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 16, 23, 7, 959161, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
