# Generated by Django 4.2 on 2023-06-14 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 14, 4, 48, 229872, tzinfo=datetime.timezone.utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
