# Generated by Django 4.2 on 2023-06-16 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 16, 23, 7, 939641, tzinfo=datetime.timezone.utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
