# Generated by Django 4.2 on 2023-06-16 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 16, 28, 6, 312610, tzinfo=datetime.timezone.utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
